import React from "react";
import { Link } from "react-router-dom";


// The props that MovieLists is getting here are passed as state from App.js. State was set to the array of objects called "movies". Movies gets mapped over and for every object creates a movie card to add to the list. The props passed down to the MovieDetails function include title, director and metascore. The object containing those props is given the name "movie". The Link is set up around the entire card and when clicked on will return the card generated by Movie.js with the appropriate id.
const MovieList = (props) => {
  return (
    <div className="movie-list">
      {props.movies.map((movie) => (
        <MovieDetails key={movie.id} movie={movie} />
      ))}
    </div>
  );
};

function MovieDetails({ movie }) {
  const { title, director, metascore } = movie;
  console.log("movie details", movie);
  return (
    <Link to={`/movies/${movie.id}`}>
      <div className="movie-card">
        <h2>{title}</h2>
        <div className="movie-director">
          Director: <em>{director}</em>
        </div>
        <div className="movie-metascore">
          Metascore: <strong>{metascore}</strong>
        </div>
      </div>
    </Link>
  );
}

export default MovieList;
